name: Weekly README.md update
on:
  workflow_dispatch: # Allows you to run it manually from the Actions tab
jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true # Speeds up subsequent runs even more
          # The version of Python to set UV_PYTHON to
          python-version: "3.14.3"
          
      - name: Run agent with uv
        # 'uv run' will automatically handle dependencies if defined in the script
        env:
          # Mapping the secret to the environment variable
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: uv run agent.py
      
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "docs: weekly stack refresh ($GITHUB_RUN_ID)" || echo "No changes found"
          git push
